{
  "name": "Release",
  "on": {
    "release": {
      "types": [
        "published"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "permissions": {
        "id-token": "write"
      },
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Set up Python",
          "uses": "actions/setup-python@v4",
          "with": {
            "python-version": "3.11"
          }
        },
        {
          "name": "Install dependencies",
          "run": "python -m pip install .[dev]"
        },
        {
          "name": "Tests",
          "run": "python -m pytest tests"
        },
        {
          "name": "Build package",
          "run": "python -m build"
        },
        {
          "name": "Publish package distributions to PyPI",
          "uses": "pypa/gh-action-pypi-publish@release/v1"
        }
      ]
    }
  }
}