{
  "name": "Test",
  "on": {
    "workflow_dispatch": {},
    "pull_request": {}
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Set up Python",
          "uses": "actions/setup-python@v4",
          "with": {
            "python-version": "3.11"
          }
        },
        {
          "name": "Install dependencies",
          "run": "python -m pip install .[dev]"
        },
        {
          "name": "Check format",
          "run": "python -m black --check ."
        },
        {
          "name": "Check lints",
          "run": "python -m ruff check ."
        },
        {
          "name": "Tests",
          "run": "python -m pytest"
        }
      ]
    }
  }
}